version: "3"
  services:
    testsman-backend:
      build: ./backend
      image: testsman-backend:latest
      ports:
        - "8080:8080"
      volumes:
        - /home/ubuntu/images:/static/images/

    testsman-frontend:
      build: ./frontend
      image: testsman-frontend:latest
      ports:
        - "80:3000"
      volumes:
        - /home/ubuntu/images:/static/images/

  #   nginx:
  #     container_name: nginx-proxy
  #     image: "nginx:test"
  #     ports:
  #       - "80:80"
  #     networks:
  #       - proxy
     
  # networks:

  #   proxy:
  #     driver: bridge