version: '3'
services:
  testsman-backend:
    build: ./backend
    image: testsman-backend:latest
    ports:
      - '8080:8080'

  testsman-frontend:
    build: ./frontend
    image: testsman-frontend:latest
    ports:
      - '80:3000'

  #   nginx:
  #     container_name: nginx-proxy
  #     image: "nginx:test"
  #     ports:
  #       - "80:80"
  #     networks:
  #       - proxy

  # networks:

  #   proxy:
  #     driver: bridge
