version: '3' 
services: 
    testsman-backend: 
        build: ./backend 
        image: testsman-backend:latest
        ports: 
            - "8080:8080"
        # volumes:
        #     - /home/ubuntu/images/profile:/static/image/profile
        #     - /home/ubuntu/images/diary:/static/image/diary